"""CASCADE on delete

Revision ID: 157c16c5b68c
Revises: 88b1b92f50ef
Create Date: 2024-06-15 16:21:03.217047

"""
from alembic import op
import sqlalchemy as sa

from app import naming_convention

# revision identifiers, used by Alembic.
revision = '157c16c5b68c'
down_revision = '88b1b92f50ef'
branch_labels = None
depends_on = None


def upgrade():
    from sqlalchemy.orm.session import Session
    session = Session(bind=op.get_bind())
    session.execute('PRAGMA foreign_keys = ON;')
    session.commit()

    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('interaction', schema=None, naming_convention=naming_convention) as batch_op:
        batch_op.drop_constraint('fk_interaction_participation_participation', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_interaction_participation_participation'), 'participation', ['participation'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('message', schema=None, naming_convention=naming_convention) as batch_op:
        batch_op.create_foreign_key(batch_op.f('fk_message_participation_participation'), 'participation', ['participation'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('participation', schema=None, naming_convention=naming_convention) as batch_op:
        batch_op.drop_constraint('fk_participation_user_study_id_userstudy', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_participation_user_study_id_userstudy'), 'userstudy', ['user_study_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('participation', schema=None, naming_convention=naming_convention) as batch_op:
        batch_op.drop_constraint('fk_interaction_participation_participation', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_interaction_participation_participation'), 'participation', ['participation'], ['id'])

    with op.batch_alter_table('message', schema=None, naming_convention=naming_convention) as batch_op:
        batch_op.drop_constraint('fk_message_participation_participation', type_='foreignkey')

    with op.batch_alter_table('interaction', schema=None, naming_convention=naming_convention) as batch_op:
        batch_op.drop_constraint('fk_participation_user_study_id_userstudy', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_participation_user_study_id_userstudy'), 'userstudy', ['user_study_id'], ['id'])

    # ### end Alembic commands ###
